name: GitHub Actions Demo
on: [push]
jobs:
  screenshot:
    name: Screenshot
    runs-on: windows-latest

    steps:

    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://github.com/swinton/screenshot-website
        destination: screenshot.png

    - name: Commit file
      uses: swinton/commit@v2.x
      env:
        GH_TOKEN: ${{ secrets.TOKEN_GH }}
      with:
        files: |
          myfile
        commit-message: Committing ./myfile
        ref: refs/heads/my-branch
