name: screenshots ci actions
on:
  push:
    branches:
    - main
defaults:
  run:
    working-directory: src
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://github.com/swinton/screenshot-website
        destination: screenshot.png
        
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
          name: screenshot
          path: screenshot.png

    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: screenshot
        path: screenshot.png

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: screenshot.png

#     - name: Commit file
#       uses: swinton/commit@v2.x
#       env:
#         GH_TOKEN: ${{ secrets.TOKEN_GH }}
#       with:
#         files: |
#           screenshot.png
#         commit-message: Committing ./myfile
#         ref: refs/heads/main
