name: GitHub Actions Demo
on: [push]
jobs:
  screenshot:
    name: Screenshot
    runs-on: windows-latest

    steps:

    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://github.com/swinton/screenshot-website
        destination: screenshot.png
        
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
          name: code-coverage-report
          path: screenshot.png

#     - name: Commit file
#       uses: swinton/commit@v2.x
#       env:
#         GH_TOKEN: ${{ secrets.TOKEN_GH }}
#       with:
#         files: |
#           screenshot.png
#         commit-message: Committing ./myfile
#         ref: refs/heads/main
